source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RFFeatureToggle_Example', :exclusive => true do
  pod "RFFeatureToggle", :path => "../"
end

target 'RFFeatureToggle_Tests', :exclusive => true do
  pod "RFFeatureToggle", :path => "../"

  pod 'FBSnapshotTestCase/Core'
  pod 'OHHTTPStubs'
  pod 'OCMock'
end
