language: objective-c
cache: cocoapods
osx_image: xcode8.2

install:
- gem install slather

script:
- xctool -project "RFFeatureToggle.xcodeproj" -scheme "RFFeatureToggle" build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
-  bash <(curl -s https://codecov.io/bash)
